name: OpenShift Client Downloader
description: Downloads OpenShift clients :)

inputs:
  crc:
    description: crc
    required: false
  kamel:
    description: Camel-k
    required: false
  helm:
    description: Helm
    required: false
  kn:
    description: Knative
    required: false
  oc:
    description: oc
    required: false
  openshift-install:
    description: openshift-install
    required: false
  odo:
    description: odo
    required: false
  opm:
    description: opm
    required: false
  tkn:
    description: Tekton
    required: false
outputs:
  installed:
    description: 'JSON object describing the versions that were installed. eg. { kn: { version: "0.17.3", cached: true } }'
runs:
  using: node12
  main: dist/index.js
