name: Test
on:
  push:
  workflow_dispatch:

jobs:
  install:
    name: Installation Example
    strategy:
      fail-fast: false
      matrix:
        os: [ "macos-latest", "windows-latest", "ubuntu-20.04" ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: ./
        id: install_clients
        with:
          kamel: "1"
          tkn: "v0.13.1"
          oc: "3"
          openshift-install: "4.x"    # Not available on windows
          odo: "latest"
          helm: "3"
          kn: "0.17"

      - name: Echo output of installer
        if: always()
        run: echo "${{ steps.install_clients.outputs.installed }}"
