name: Test
on:
  push:
  workflow_dispatch:


jobs:
  install:
    name: Installation Example
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          tkn: "v0.13.1"
          odo: "2.0.3"
          helm: "3"
          kn: "0.17"
